project:
  type: website
  output-dir: _site

website:
  title: "R for GIS and Remote Sensing Tutorials"
  description: "Step-by-step tutorials for spatial data analysis, map making, and remote sensing in R."
  site-url: https://dicksonmbeya.com/rforgisrstutorials
  navbar:
    logo: assets/images/logo.png
    left:
      - href: index.qmd
        text: Home
      - text: Tutorials
        menu:
          - href: tutorials/index.qmd
            text: All Tutorials
          - href: tutorials/install-r.qmd
            text: Getting Started
      - href: about.qmd
        text: Author
    right:
      - icon: github
        href: https://github.com/dickson-mbeya/rforgisrstutorials

  sidebar:
    style: docked
    search: true
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
      - section: "Getting Started"
        contents:
          - tutorials/install-r.qmd
          - tutorials/r-basics.qmd
          - tutorials/install-packages.qmd
          - tutorials/make-map.qmd
      - section: "Vector Data Analysis"
        contents:
          - tutorials/queries.qmd
          - tutorials/map-projections.qmd
          - tutorials/geometric-operations.qmd
      - section: "Raster Data Analysis"
      - section: "Remote Sensing in R"
      - section: "Google Earth Engine in R"
      - section: "Case studies"
        
          

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: assets/css/custom.scss
    toc: true
    toc-depth: 3
    code-copy: true
    smooth-scroll: true

    execute:
      freeze: auto
      echo: true
      warning: false
      message: false
    